SWORD_IRON = 0x01
SWORD_SLIM = 0x02
SWORD_STEEL = 0x03
SWORD_SILVER = 0x04
BLADE_IRON = 0x05
BLADE_STEEL = 0x06
BLADE_SILVER = 0x07
SWORD_VENIN = 0x08
SWORD_RAPIER = 0x09
SWORD_MKATTI = 0x0A
SWORD_BRAVE = 0x0B
SWORD_SHAMSIR = 0x0C
SWORD_KILLER = 0x0D
SWORD_ARMORSLAYER = 0x0E
SWORD_WYRMSLAYER = 0x0F
SWORD_LIGHTBRAND = 0x10
SWORD_RUNESWORD = 0x11
SWORD_LANCEREAVER = 0x12
SWORD_ZANBATO = 0x13
LANCE_IRON = 0x14
LANCE_SLIM = 0x15
LANCE_STEEL = 0x16
LANCE_SILVER = 0x17
LANCE_VENIN = 0x18
LANCE_BRAVE = 0x19
LANCE_KILLER = 0x1A
LANCE_HORSESLAYER = 0x1B
LANCE_JAVELIN = 0x1C
LANCE_SPEAR = 0x1D
LANCE_AXEREAVER = 0x1E
AXE_IRON = 0x1F
AXE_STEEL = 0x20
AXE_SILVER = 0x21
AXE_VENIN = 0x22
AXE_BRAVE = 0x23
AXE_KILLER = 0x24
AXE_HALBERD = 0x25
AXE_HAMMER = 0x26
AXE_DEVIL = 0x27
AXE_HANDAXE = 0x28
AXE_TOMAHAWK = 0x29
AXE_SWORDREAVER = 0x2A
AXE_SWORDSLAYER = 0x2B
AXE_HATCHET = 0x2C
BOW_IRON = 0x2D
BOW_STEEL = 0x2E
BOW_SILVER = 0x2F
BOW_VENIN = 0x30
BOW_KILLER = 0x31
BOW_BRAVE = 0x32
BOW_SHORTBOW = 0x33
BOW_LONGBOW = 0x34
BALLISTA_REGULAR = 0x35
BALLISTA_LONG = 0x36
BALLISTA_KILLER = 0x37
ANIMA_FIRE = 0x38
ANIMA_THUNDER = 0x39
ANIMA_ELFIRE = 0x3A
ANIMA_BOLTING = 0x3B
ANIMA_FIMBULVETR = 0x3C
ANIMA_FORBLAZE = 0x3D
ANIMA_EXCALIBUR = 0x3E
LIGHT_LIGHTNING = 0x3F
LIGHT_SHINE = 0x40
LIGHT_DIVINE = 0x41
LIGHT_PURGE = 0x42
LIGHT_AURA = 0x43
LIGHT_LUCE = 0x44
DARK_FLUX = 0x45
DARK_LUNA = 0x46
DARK_NOSFERATU = 0x47
DARK_ECLIPSE = 0x48
DARK_FENRIR = 0x49
DARK_GLEIPNIR = 0x4A
STAFF_HEAL = 0x4B
STAFF_MEND = 0x4C
STAFF_RECOVER = 0x4D
STAFF_PHYSIC = 0x4E
STAFF_FORTIFY = 0x4F
STAFF_RESTORE = 0x50
STAFF_SILENCE = 0x51
STAFF_SLEEP = 0x52
STAFF_BERSERK = 0x53
STAFF_WARP = 0x54
STAFF_RESCUE = 0x55
STAFF_TORCH = 0x56
STAFF_REPAIR = 0x57
STAFF_UNLOCK = 0x58
STAFF_BARRIER = 0x59
AXE_DRAGON = 0x5A
BOOSTER_HP = 0x5B
BOOSTER_POW = 0x5C
BOOSTER_SKL = 0x5D
BOOSTER_SPD = 0x5E
BOOSTER_LCK = 0x5F
BOOSTER_DEF = 0x60
BOOSTER_RES = 0x61
BOOSTER_MOV = 0x62
BOOSTER_CON = 0x63
HEROCREST = 0x64
KNIGHTCREST = 0x65
ORIONSBOLT = 0x66
ELYSIANWHIP = 0x67
GUIDINGRING = 0x68
CHESTKEY = 0x69
DOORKEY = 0x6A
LOCKPICK = 0x6B
VULNERARY = 0x6C
ELIXIR = 0x6D
PUREWATER = 0x6E
ANTITOXIN = 0x6F
TORCH = 0x70
DELPHISHIELD = 0x71
MEMBERCARD = 0x72
SILVERCARD = 0x73
WHITEGEM = 0x74
BLUEGEM = 0x75
REDGEM = 0x76
GOLD = 0x77
LANCE_REGINLEIF = 0x78
CHESTKEY_BUNDLE = 0x79
MINE = 0x7A
LIGHTRUNE = 0x7B
HOPLON_SHIELD = 0x7C
FILLAS_MIGHT = 0x7D
NINISS_GRACE = 0x7E
THORS_IRE = 0x7F
SETS_LITANY = 0x80
SWORD_SHADOWKILLR = 0x81
LANCE_BRIGHTLANCE = 0x82
AXE_FIENDCLEAVER = 0x83
BOW_BEACONBOW = 0x84
SWORD_SIEGLINDE = 0x85
AXE_BATTLEAXE = 0x86
LIGHT_IVALDI = 0x87
MASTERSEAL = 0x88
METISSTOME = 0x89
HEAVENSEAL = 0x8A
MONSTER_SHARPCLAW = 0x8B
STAFF_LATONA = 0x8C
LANCE_DRAGON = 0x8D
LANCE_VIDOFNIR = 0x8E
DARK_NAGLFAR = 0x8F
MONSTER_WRETCHAIR = 0x90
SWORD_AUDHULMA = 0x91
LANCE_SIEGMUND = 0x92
AXE_GARM = 0x93
BOW_NIDHOGG = 0x94
LANCE_HEAVYSPEAR = 0x95
LANCE_SHORTSPEAR = 0x96
OCEANSEAL = 0x97
LUNARBRACE = 0x98
SOLARBRACE = 0x99
GOLD_1 = 0x9A
GOLD_5 = 0x9B
GOLD_10 = 0x9C
GOLD_50 = 0x9D
GOLD_100 = 0x9E
GOLD_3000 = 0x9F
GOLD_5000 = 0xA0
SWORD_WINDSWORD = 0xA1
VULNERARY_2 = 0xA2
UNK_GREENNOTE = 0xA3
UNK_REDNOTE = 0xA4
DANCE = 0xA5
NIGHTMARE = 0xA6
DEMONSTONE = 0xA7
DEMONLIGHT = 0xA8
RAVAGER = 0xA9
DIVINESTONE = 0xAA
MONSTER_DEMONSURG = 0xAB
MONSTER_SHADOWSHT = 0xAC
MONSTER_ROTTENCLW = 0xAD
MONSTER_FETIDCLW = 0xAE
MONSTER_VENINCLW = 0xAF
MONSTER_LTHLTALON = 0xB0
MONSTER_FIREFANG = 0xB1
MONSTER_HELLFANG = 0xB2
MONSTER_EVILEYE = 0xB3
MONSTER_CRIMSNEYE = 0xB4
MONSTER_STONE = 0xB5
ANIMA_AIRCALIBUR = 0xB6
JUNAFRUIT = 0xB7
GOLD_150 = 0xB8
GOLD_200 = 0xB9
BLACKGEM = 0xBA
GOLDGEM = 0xBB
UNK_BC = 0xBC
UNK_BD = 0xBD
UNK_BE = 0xBE
UNK_BF = 0xBF
UNK_C0 = 0xC0
UNK_C1 = 0xC1
UNK_CC = 0xCC
UNK_CD = 0xCD

ITEM_TYPE_SWORD = 0
ITEM_TYPE_LANCE = 1
ITEM_TYPE_AXE = 2
ITEM_TYPE_BOW = 3
ITEM_TYPE_STAFF = 4
ITEM_TYPE_ANIMA = 5
ITEM_TYPE_LIGHT = 6
ITEM_TYPE_DARK = 7
ITEM_TYPE_ITEM = 9  # non-weapon items (vulneraries, etc.)
# There are other item types as well (up to 12), but these are the ones we care about

WIELDABLE_TYPES = [
    ITEM_TYPE_SWORD,
    ITEM_TYPE_LANCE,
    ITEM_TYPE_AXE,
    ITEM_TYPE_BOW,
    ITEM_TYPE_STAFF,
    ITEM_TYPE_ANIMA,
    ITEM_TYPE_LIGHT,
    ITEM_TYPE_DARK,
]

MELEE_ATTACK_TYPES = [
    ITEM_TYPE_SWORD,
    ITEM_TYPE_LANCE,
    ITEM_TYPE_AXE,
]

RANGED_ATTACK_TYPES = [ITEM_TYPE_BOW, ITEM_TYPE_ANIMA, ITEM_TYPE_LIGHT, ITEM_TYPE_DARK]

ATTACK_CAPABLE_TYPES = [
    ITEM_TYPE_SWORD,
    ITEM_TYPE_LANCE,
    ITEM_TYPE_AXE,
    ITEM_TYPE_BOW,
    ITEM_TYPE_ANIMA,
    ITEM_TYPE_LIGHT,
    ITEM_TYPE_DARK,
]


# WEXP required for each weapon rank
WEAPON_RANK_E = 1
WEAPON_RANK_D = 31
WEAPON_RANK_C = 71
WEAPON_RANK_B = 121
WEAPON_RANK_A = 181
WEAPON_RANK_S = 251

WEAPON_RANDOMIZER_CANDIDATES = [
    SWORD_IRON,
    SWORD_SLIM,
    SWORD_STEEL,
    SWORD_SILVER,
    BLADE_IRON,
    BLADE_STEEL,
    BLADE_SILVER,
    SWORD_VENIN,
    # SWORD_RAPIER,
    SWORD_BRAVE,
    # SWORD_SHAMSIR,
    SWORD_KILLER,
    SWORD_ARMORSLAYER,
    SWORD_WYRMSLAYER,
    SWORD_LIGHTBRAND,
    SWORD_RUNESWORD,
    SWORD_LANCEREAVER,
    SWORD_ZANBATO,
    LANCE_IRON,
    LANCE_SLIM,
    LANCE_STEEL,
    LANCE_SILVER,
    LANCE_VENIN,
    LANCE_BRAVE,
    LANCE_KILLER,
    LANCE_HORSESLAYER,
    LANCE_JAVELIN,
    LANCE_SPEAR,
    LANCE_AXEREAVER,
    AXE_IRON,
    AXE_STEEL,
    AXE_SILVER,
    AXE_VENIN,
    AXE_BRAVE,
    AXE_KILLER,
    AXE_HALBERD,
    AXE_HAMMER,
    AXE_DEVIL,
    AXE_HANDAXE,
    AXE_TOMAHAWK,
    AXE_SWORDREAVER,
    AXE_SWORDSLAYER,
    AXE_HATCHET,
    BOW_IRON,
    BOW_STEEL,
    BOW_SILVER,
    BOW_VENIN,
    BOW_KILLER,
    BOW_BRAVE,
    BOW_SHORTBOW,
    BOW_LONGBOW,
    ANIMA_FIRE,
    ANIMA_THUNDER,
    ANIMA_ELFIRE,
    ANIMA_BOLTING,
    ANIMA_FIMBULVETR,
    # ANIMA_EXCALIBUR,
    LIGHT_LIGHTNING,
    LIGHT_SHINE,
    LIGHT_DIVINE,
    LIGHT_PURGE,
    LIGHT_AURA,
    LIGHT_LUCE,
    DARK_FLUX,
    DARK_LUNA,
    DARK_NOSFERATU,
    DARK_ECLIPSE,
    DARK_FENRIR,
    # DARK_GLEIPNIR,
    STAFF_HEAL,
    STAFF_MEND,
    STAFF_RECOVER,
    STAFF_PHYSIC,
    STAFF_FORTIFY,
    STAFF_RESTORE,
    STAFF_SILENCE,
    STAFF_SLEEP,
    STAFF_BERSERK,
    STAFF_WARP,
    STAFF_RESCUE,
    STAFF_TORCH,
    STAFF_REPAIR,
    STAFF_UNLOCK,
    STAFF_BARRIER,
    AXE_DRAGON,
    # LANCE_REGINLEIF,
    # SWORD_SIEGLINDE,
    AXE_BATTLEAXE,
    # LIGHT_IVALDI,
    # STAFF_LATONA,
    LANCE_DRAGON,
    # LANCE_VIDOFNIR,
    # DARK_NAGLFAR,
    # SWORD_AUDHULMA,
    # LANCE_SIEGMUND,
    # AXE_GARM,
    # BOW_NIDHOGG,
    LANCE_HEAVYSPEAR,
    LANCE_SHORTSPEAR,
    SWORD_WINDSWORD,
]

EXCLUDE_FROM_SHOPS = [
    BOW_VENIN,
    AXE_VENIN,
    LANCE_VENIN,
    SWORD_VENIN,
]

EXCLUDE_FROM_INV_RANDOMIZATION = [
    AXE_HATCHET,
]

# Item IDs to avoid adding to inventories
UNUSABLE_ITEMS = [
    0x0A,
    0x3D,
    0x44,
    0x7A,
    0x7B,
    0x7D,
    0x7E,
    0x7F,
    0x80,
    0x8A,
    0xBC,
    0xBD,
    0xBE,
    0xBF,
    0xC0,
    0xC1,
    0xCC,
    0xCD,
    0x35,
    0x36,
    0x37,
]

RANDOMIZABLE_CONSUMABLES = [
    CHESTKEY,
    DOORKEY,
    VULNERARY,
    ELIXIR,
    PUREWATER,
    ANTITOXIN,
    TORCH,
]

STAT_BOOSTERS = [
    BOOSTER_HP,  # HP
    BOOSTER_POW,  # M/S
    BOOSTER_SKL,  # Skl
    BOOSTER_SPD,  # Spd
    BOOSTER_LCK,  # Lck
    BOOSTER_DEF,  # Def
    BOOSTER_RES,  # Res
    BOOSTER_MOV,  # Mov
    BOOSTER_CON,  # Con
]
